# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 08:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ml', '0002_auto_20170704_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 8, 24, 48, 755722)),
        ),
        migrations.AddField(
            model_name='userquery',
            name='pclass',
            field=models.CharField(default='about', max_length=20),
        ),
        migrations.AddField(
            model_name='userquery',
            name='prob',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquery',
            name='session',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
