# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ml', '0004_auto_20170704_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='prob',
            field=models.FloatField(default=0.0),
        ),
    ]
