# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ml', '0005_auto_20170704_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='backend',
            field=models.CharField(default='logreg', max_length=10),
        ),
    ]
